### ISSUE TITLE
Could not find resource file "/apps/sketch/js/vendor/requirejs/require.js" 

### ISSUE THREAD

**Issue by Olhur** [ChristophWurst/sketch#37]
Hello!
I have just installed Sketch on my ownCloud 8.2.2, but it doesn't seem to work. The admin log shows 
`Could not find resource file "/apps/sketch/js/vendor/requirejs/require.js" `.

Do you have any idea how to solve that issue or where is it coming from? 

Best regards!
Filip

**Comment by ChristophWurst** [comment]
Hey @Olhur,
how did you install the app? Did you use the packaged version from the app store or a developer snapshot from github?
This looks like js-dependencies are not available, which should not happen with the appstore version.
Thanks for reporting!
Christoph

**Comment by Olhur** [comment]
Indeed, this was an issue - I was trying to instal Sketch directly from Github. Installation from the app store was successful. Thanks!

**Comment by ChristophWurst** [comment]
> Indeed, this was an issue - I was trying to instal Sketch directly from Github. Installation from the app store was successful. Thanks!

Great! If find any other issues or enhancements, please open a new issue if it does not already exist. Thanks and happy sketching ;-)
