### ISSUE TITLE
How can install in nexcloud 12

### ISSUE THREAD

**Issue by johnfelipe** [ChristophWurst/sketch#41]
Stay alert of you cheatsheet or steps
Tnks

**Comment by ChristophWurst** [comment]
Hi,

this app is unmaintained. I don't know whether it would work with Nextcloud 12, hence I'm not investing any time into it.

**Comment by johnfelipe** [comment]
I want to try, can u share me instructions to how test or how install new
apps?

**Comment by ChristophWurst** [comment]
Check out https://docs.nextcloud.com/server/12/developer_manual/app/index.html#id1. For any further help please use the forum at help.nextcloud.com. Thanks.
